agents_list = [
    {
        'name': 'Agent 1: DDQN - policy 1',
        'path': '../agents/log/texas-holdem-unlimited/ddqn/policy1/policy1.pth',
        'hidden_sizes': [256, 256, 256, 256, 256],
        'lr': 1e-3,
        'gamma': 0.9,
        'n_step': 7,
        'eps_test': 0.05,
    },
    {
        'name': 'Agent 2: DDQN - policy 2',
        'path': '../agents/log/texas-holdem-unlimited/ddqn/policy2/policy2.pth',
        'hidden_sizes': [512, 512, 512],
        'lr': 5e-4,
        'gamma': 0.99,
        'n_step': 5,
        'eps_test': 0.01,
    },
    {
        'name': 'Agent 3: DQN - policy 1',
        'path': '../agents/log/texas-holdem-unlimited/dqn/policy1/policy1.pth',
        'hidden_sizes': [256, 256, 256, 256, 256],
        'lr': 1e-3,
        'gamma': 0.9,
        'n_step': 7,
        'eps_test': 0.05,
    },
    {
        'name': 'Agent 4: DuelingDQN - policy 1',
        'path': '../agents/log/texas-holdem-unlimited/duelingdqn/policy1/policy1.pth',
        'hidden_sizes': [512, 512, 512],
        'lr': 1e-3,
        'gamma': 0.99,
        'n_step': 5,
        'eps_test': 0.05,
    },
    {
        'name': 'Agent 5: Self play on agent 1',
        'path': '../agents/log/self-play/ddqn/policy1/policy1.pth',
        'hidden_sizes': [256, 256, 256, 256, 256],
        'lr': 1e-3,
        'gamma': 0.9,
        'n_step': 7,
        'eps_test': 0.05,
    },
    {
        'name': 'Agent 6: Continued self play on agent 5',
        'path': '../agents/log/self-play/ddqn/policy1.1/policy1.1.pth',
        'hidden_sizes': [256, 256, 256, 256, 256],
        'lr': 1e-3,
        'gamma': 0.9,
        'n_step': 7,
        'eps_test': 0.05,
    }
]
